import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Mint from './mint';
import { ConnectWallet,useContract, useContractWrite, Web3Button, useAddress } from '@thirdweb-dev/react'

const inter = Inter({ subsets: ['latin'] })


export default function Home() {
  return (
    <>
      <Head>
        <title>MINT YOUR NFT</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div>
            <ConnectWallet />
        </div>
        
        <div className={styles.center}>
          <div className={styles.thirteen}>
            <Image
              src="/035.jpg"
              alt="13"
              width={250}
              height={250}
              priority
            />
          </div>
        </div>
        <Mint />
        <div className={styles.grid}>
          <a
            href="https://mumbaifaucet.com/"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Get Matic <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Get Matic token to mint Our NFT.
            </p>
          </a>

          <a
            href="https://testnets.opensea.io/collection/100daysofsolidity-1"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Check Collection <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              If you are done minting you can check your NFTs here.
            </p>
          </a>

          <a
            href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Guide to Recreate <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              This is the github repository it contains all about  how the NFTs was created.
            </p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Follow on Twitter <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Join me on twitter on my #100Days of Solidity Challenge
            </p>
          </a>
        </div>
      </main>
    </>
  )
}
